<?php if ($this->pageCount): ?>
    <div class="pagination pagination-centered">
        <ul>
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $this->url(
                    $this->route,
                    array(),
                    array('query' => array($this->searchable->currentPageParamName() => $this->previous))
                ); ?>">«</a></li>
            <?php else: ?>
                <li class="disabled"><span>«</span></li>
            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li><a href="<?php echo $this->url(
                        $this->route,
                        array(),
                        array('query' => array($this->searchable->currentPageParamName() => $page))
                    ); ?>"><?php echo $page; ?></a></li>
                <?php else: ?>
                    <li class="active"><span><?php echo $page; ?></span></li>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $this->url(
                    $this->route,
                    array(),
                    array('query' => array($this->searchable->currentPageParamName() => $this->next))
                ); ?>">»</a></li>
            <?php else: ?>
                <li class="disabled"><span>»</span></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>
